### ISSUE TITLE
Install on Atom 124 fails

### ISSUE THREAD

**Issue by backspaces** [mick/geojson-preview#10]
During the install of geojson--preview, I get:

npm ERR! runas@0.5.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@0.5.4 install script.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

The whole error printout is here:
https://github.com/backspaces/play/blob/master/geojsonAtomError.txt

Let me know if this should go to a different repo's issues.  I know this release of Atom had many deep changes, so the issue may be theirs!

   -- Owen

**Comment by backspaces** [comment]
APM info:
apm -v 
apm  0.92.0
npm  1.4.4
node 0.10.26
python 2.7.5
git 2.1.0

Just to be clear: It is the case that Atom has their own versions of node and npm and the others above, right?

**Comment by kevinsawicki** [comment]
This looks like the same issue as #9

**Comment by mick** [comment]
@backspaces thanks for reporting the issue this should be fixed in `0.3.3` thanks to @kevinsawicki in #11
