### ISSUE TITLE
package does not show points

### ISSUE THREAD

**Issue by d1b1** [mick/geojson-preview#7]
I am trying out the package with the following geojson file. 

https://github.com/d1b1/geojson-makers/blob/master/Ireland.geojson

Not certain is I am missing something.

**Comment by mick** [comment]
Not just you. Looks like something got broken with a new version of atom... I'll fix this soon.

**Comment by mick** [comment]
@d1b1 This should be fixed in 0.3.0. Can you update and let me know. Thanks!
