### ISSUE TITLE
Does not work with the latest version of atom 0.121.0

### ISSUE THREAD

**Issue by gingermusketeer** [mick/geojson-preview#9]
![screen shot 2014-08-14 at 11 26 11 am](https://cloud.githubusercontent.com/assets/1177034/3914099/42dafd04-2341-11e4-86c0-100241522740.png)

**Comment by mick** [comment]
@gingermusketeer  thanks for reporting the issue this should be fixed in `0.3.3` thanks to @kevinsawicki in #11
